### ISSUE TITLE
Glorious expansion isn't researched

### ISSUE THREAD

**Issue by tuxayo** [SlavomirSlovenkai/Kiara#6]
I just tried 64fa277 on two matches and let the game run after Kiara's victory and even after a while having a wonder, it doesn't research glorious expansion. While Petra does.

Thanks for making this, it's fun watching AI fights ^^

**Comment by SlavomirSlovenkai** [comment]
hmm, yes, I removed random research which is in petra, i ll add it to techs, thnx

**Comment by tuxayo** [comment]
> I removed random research that is in petra

lol so that's Petra's strategy ^^"
simple

**Comment by SlavomirSlovenkai** [comment]
Petra has wanted. Prefered and when all is reaearched then goes random in phase 3
